### ISSUE TITLE
Where do I find the electric vehicles in dynamic data ?

### ISSUE THREAD

**Issue by amitrai12018** [gsoh/VED#2]
I have found the Electric vehicle ids as 10 , 455 and 541, but locating these in the dynamic data seems very tedious. If any one tells me in which file is are these vehicles used it would be a great help? 
Thanks in Advance

**Comment by gsoh** [comment]
Hi! 

You would need to write a script to load the dynamic data and match the ids with the dynamic data.
For your information, the 3 EVs are 2013 Nissan Leaf with an advertised battery capacity of 24 kWh.
