### ISSUE TITLE
Negative SOC values for electric vehicles

### ISSUE THREAD

**Issue by davidalb97** [gsoh/VED#3]
Hello, I'm doing a study on electric car's range prediction. 
However, while I was analyzing the VED dynamic data, I found multiple instances where the SOC percentage is negative.
Does the SOC percentage represent the variation relative to the previous measure, or it is taking and invalid measure?

Thank you for your time.

**Comment by gsoh** [comment]
Hi, 

The SOC percentage should always be non-negative. There shouldn't be any data with a negative SOC percentage. I am not aware of any; where did you find the instances?
