### ISSUE TITLE
No vehicle model on static data

### ISSUE THREAD

**Issue by davidalb97** [gsoh/VED#4]
Hello, I'm doing a study on electric car's range prediction.
While analyzing the VED static data, I found no reference for the vehicle's model.
I can understand if it was not included to avoid legal issues with the car manufacturers.
It would be beneficial, if possible for for future data research, to include a vehicle model and brand column on the existing static data.

Thank you for your time.

**Comment by gsoh** [comment]
Hello, sorry for the late response.

All of the pure EV records are from 3 distinct 2013 Nissan Leaf vehicles. 2013 Nissan leaf has an advertised battery capacity of 24 kWh.
